name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install gcc libglib2.0-0 libgtk-4-1 libgtk-4-dev ninja-build -y
        sudo snap install cmake --classic

    - name: Install Deps (Windows)
      if: ${{ matrix.os == 'windows-2022' }}
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gtk4

    - name: Generate Build Files & Build (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        make all BUILD_TYPE=Release NUM_JOBS=4

    - name: Generate Build Files & Build (Windows)
      shell: msys2 {0}
      if: ${{ matrix.os == 'windows-2022' }}
      run: |
        mingw32-make all BUILD_TYPE=Release NUM_JOBS=4

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        if-no-files-found: error
        path: ./build/

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-2022' }}
      with:
        name: win-x64
        if-no-files-found: error
        path: ./build/
